export { App } from "./App/";
export { Main } from "./Main";
export { Intro } from "./Intro/";
export { About } from "./About/";
export { Header } from "./Header/";
export { Footer } from "./Footer/";
export { Contact } from "./Contact/";
export { Featured } from "./Featured/";
export { Projects } from "./Projects/";
